engines:
  eslint:
    enabled: true
ratings:
  paths:
  - "src/**"
exclude_paths:
- "dist/*"
- "example/**/*"
- "Gruntfile.js"
- "gulpfile.js"
- "*.md"
- "LICENSE"
- "*.json"
- ".codeclimate.yml"
- ".eslintrc"
- ".gitattributes"
- ".gitignore"
