name: d3.compose
baseurl: /d3.compose
url: http://csnw.github.io/d3.compose
github: https://github.com/csnw/d3.compose

# TODO Load from package.json/bower.json
version: 0.12.14

exclude:
- Gemfile
- Gemfile.lock
- README.md
- bower_components
- node_modules
- tmp

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions:
  - fenced_code_blocks
sass:
  style: :compressed
  sass_dir: _css
