name: d3.chart.multi
baseurl: /d3.chart.multi
url: http://csnw.github.io/d3.chart.multi

exclude:
- Gemfile
- Gemfile.lock
- README.md
- node_modules
- bower_components
- .grunt

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions:
  - fenced_code_blocks
sass:
  style: :compressed
  sass_dir: _css